import 'package:re_highlight/re_highlight.dart';

final langLowResRMX = Mode(
  refs: {},
  name: "LowResRMX",
  caseInsensitive: true,
  illegal: "^.",
  keywords: {
    "\$pattern": "[a-zA-Z][a-zA-Z0-9_]*\\.?[a-zA-Z0-9_][a-zA-Z0-9_]*[\$%]?",
    "keyword": [
      "ABS",
      "ACOS",
      "ADD",
      "AND",
      "ASC",
      "ASIN",
      "AT",
      "ATAN",
      "ATTR",
      "BG",
      "BIN\$",
      "CALL",
      "CEIL",
      "CELL",
      "CELL.A",
      "CELL.C",
      "CHAR",
      "CHR\$",
      "CLAMP",
      "CLS",
      "CLW",
      "COLOR",
      "COMPAT",
      "COPY",
      "COS",
      "CURSOR.X",
      "CURSOR.Y",
      "DATA",
      "DEC",
      "DIM",
      "DMA",
      "DO",
      "EASE",
      "ELSE",
      "EMITTER",
      "END",
      "ENVELOPE",
      "EXIT",
      "EXP",
      "FILE\$",
      "FILES",
      "FILL",
      "FLIP",
      "FONT",
      "FOR",
      "FSIZE",
      "GLOBAL",
      "GOSUB",
      "GOTO",
      "HCOS",
      "HEX\$",
      "HIT",
      "HSIN",
      "HTAN",
      "IF",
      "INC",
      "INKEY\$",
      "INPUT",
      "INSTR",
      "INT",
      "KEYBOARD",
      "LEFT\$",
      "LEN",
      "LET",
      "LFO",
      "LFO.A",
      "LOAD",
      "LOCATE",
      "LOG",
      "LOOP",
      "MAX",
      "MCELL",
      "MCELL.A",
      "MCELL.C",
      "MESSAGE",
      "MID\$",
      "MIN",
      "MOD",
      "MUSIC",
      "NEXT",
      "NOT",
      "NUMBER",
      "OFF",
      "ON",
      "OR",
      "PAL",
      "PALETTE",
      "PARTICLE",
      "PAUSE",
      "PEEK",
      "PEEKL",
      "PEEKW",
      "PI",
      "PLAY",
      "POKE",
      "POKEL",
      "POKEW",
      "PRINT",
      "PRIO",
      "RANDOMIZE",
      "RASTER",
      "READ",
      "REM",
      "REPEAT",
      "RESTORE",
      "RETURN",
      "RIGHT\$",
      "RND",
      "ROL",
      "ROM",
      "ROR",
      "SAFE.B",
      "SAFE.L",
      "SAFE.R",
      "SAFE.T",
      "SAVE",
      "SCROLL",
      "SCROLL.X",
      "SCROLL.Y",
      "SGN",
      "SHOWN.H",
      "SHOWN.W",
      "SIN",
      "SIZE",
      "SKIP",
      "SOUND",
      "SOURCE",
      "SPRITE",
      "SPRITE.A",
      "SPRITE.C",
      "SPRITE.X",
      "SPRITE.Y",
      "SQR",
      "STEP",
      "STOP",
      "STR\$",
      "SUB",
      "SWAP",
      "SYSTEM",
      "TAN",
      "TAP",
      "TEXT",
      "THEN",
      "TIMER",
      "TINT",
      "TO",
      "TOUCH",
      "TOUCH.X",
      "TOUCH.Y",
      "TRACE",
      "TRACK",
      "UBOUND",
      "UNTIL",
      "VAL",
      "VBL",
      "VIEW",
      "VOLUME",
      "WAIT",
      "WAVE",
      "WEND",
      "WHILE",
      "WINDOW",
      "XOR",
    ],
  },
  contains: <Mode>[
    QUOTE_STRING_MODE,
    Mode(
        scope: 'comment',
        begin: "'",
        end: "\$",
        contains: <Mode>[
          Mode(
              scope: 'doctag',
              begin: "[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)",
              end: "(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):",
              excludeBegin: true,
              relevance: 0),
          Mode(
              begin:
                  "[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+['](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}")
        ],
        relevance: 0),
		Mode(className: 'number', begin: "\\b([0-9]+)\\b"),
    Mode(className: 'number', begin: "(\\\$[0-9a-fA-F]{1,4})"),
  ],
);
